Docugami sec 10q dataset
run-llama/llama-datasets pull request #43
Opened 2023-12-12 21:33 UTC by tjaffri

More details on how this dataset was created are here: https://github.com/docugami/KG-RAG-datasets/tree/main/sec-10-q

2023-12-12 23:12 UTC, nerdai requested changes
Just a request to not delete the other dataset `history_of_alexnet`

2023-12-12 23:12 UTC, nerdai commented on llama_datasets/history_of_alexnet/rag_dataset.json
Hey @tjaffri: not sure if you meant to do this, but can you add this file back along with its source file that appears to be deleted as well in your PR?

2023-12-13 00:15 UTC, tjaffri commented on llama_datasets/history_of_alexnet/rag_dataset.json
HI @nerdai ... I didn't delete the files... I just converted them to git lfs pointers (they were checked in incorrectly without git lfs and that caused an immediate error when I git cloned the repo). If you git clone the repo in a clean dir you will see this.

I didn't see any way to commit my files without fixing these pointers at the same time since the .gitattributes enforces all PDFs and json files need to be pointers... let me know if I am missing something.

2023-12-13 00:52 UTC, nerdai approved these changes
Thanks for the clarification. LGTM!

2023-12-13 00:53 UTC, merged